sudo: required
services:
  - docker

before_install:
  - docker build -t hansmaes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hansmaes/react-test npm test -- --coverage

after_success:
  - docker build -t hansmaes/multi-client ./client
  - docker build -t hansmaes/multi-nginx ./nginx
  - docker build -t hansmaes/multi-server ./server
  - docker build -t hansmaes/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push the images to docker hub
  - docker push hansmaes/multi-client
  - docker push hansmaes/multi-nginx
  - docker push hansmaes/multi-server
  - docker push hansmaes/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-912634645368"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"